ALTER TABLE hits ADD COLUMN utm_source VARCHAR;
ALTER TABLE hits ADD COLUMN utm_medium VARCHAR;
ALTER TABLE hits ADD COLUMN utm_campaign VARCHAR;
ALTER TABLE hits ADD COLUMN utm_term VARCHAR;
ALTER TABLE hits ADD COLUMN utm_content VARCHAR;
