{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hitkeep.fullname" . }}
  labels:
    {{- include "hitkeep.labels" . | nindent 4 }}
{{- end }}
