// Code generated by go run ./cmd/ipmeta-generate; DO NOT EDIT.
//
// HitKeep uses the IP2Location LITE database for IP geolocation.
// https://www.ip2location.com
package ipmeta

import _ "embed"

//go:embed data_city.hk.zst
var embeddedCityZSTDData []byte

//go:embed data_asn.hk.zst
var embeddedASNZSTDData []byte
