package ipmeta

// These legacy CSV-generated ranges are empty in production builds. Runtime
// lookups use the compact embedded .hk.zst assets generated by
// cmd/ipmeta-generate; tests may replace these variables with fixtures.
var embeddedCountryRanges = []geoRange{}
var embeddedCityRanges = []geoRange{}
var embeddedNetworkRanges = []networkRange{}
