name: Snapshot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snapshot:
    if: "${{ !startsWith(github.event.head_commit.message, 'chore(main): release') }}"
    uses: ./.github/workflows/pipeline.yml
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
      artifact-metadata: write
    with:
      version: snapshot-${{ github.sha }}
      meta_config: |
        type=raw,value=snapshot
        type=raw,value=main,enable={{is_default_branch}}
        type=ref,event=branch
        type=ref,event=pr
        type=sha,prefix=sha-,format=short
      upload_to_release: false
    secrets: inherit
